name: causal_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  #- _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - affine=2.3.1
  - arpack=3.7.0
  - attrs=22.1.0
  - blosc=1.21.1
  - boost-cpp=1.78.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cairo=1.16.0
  - certifi=2022.9.24
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - curl=7.86.0
  - cycler=0.11.0
  - dcor=0.5.7
  - expat=2.5.0
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - geographiclib=1.52
  - geopandas=0.12.1
  - geopandas-base=0.12.1
  - geopy=2.3.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glpk=5.0
  - gmp=6.2.1
  - gpytorch=1.9.0
  - h3-py=3.7.4
  - h3pandas=0.2.3
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - kealib=1.4.15
  #- keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  #- libgcc-ng=12.2.0
  - libgdal=3.5.3
  #- libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  #- libgomp=12.2.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  #- libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libpq=14.5
  - libprotobuf=3.21.9
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  #- libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxgboost=1.7.1
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - linear_operator=0.1.1
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - matplotlib-base=3.6.1
  - metis=5.1.0
  - mkl=2022.1.0
  - mpfr=4.1.0
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.8.7
  - ninja=1.11.0
  - nspr=4.32
  - nss=3.78
  - openjpeg=2.5.0
  - openssl=3.0.7
  - osmnx=1.2.2
  - packaging=21.3
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.37
  - pip=22.3
  - pixman=0.40.0
  - poppler=22.10.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - proj=9.1.0
  - pthread-stubs=0.4
  - py-xgboost=1.7.1
  - pycparser=2.21
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-igraph=0.10.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2022.5
  - readline=8.1.2
  - requests=2.28.1
  - seaborn=0.12.0
  - seaborn-base=0.12.0
  - setuptools=65.5.0
  - six=1.16.0
  - sleef=3.5.1
  - slicer=0.0.7
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.39.4
  - suitesparse=5.10.1
  - tbb=2021.6.0
  - texttable=1.6.4
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tk=8.6.12
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022e
  - tzdata=2022f
  - urllib3=1.26.11
  - wheel=0.37.1
  - xerces-c=3.2.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - brotlipy==0.7.0
    - cffi==1.15.1
    - click==8.1.3
    - comet-ml==3.31.20
    - configobj==5.0.6
    - contourpy==1.0.6
    - cryptography==38.0.2
    - dulwich==0.20.50
    - everett==3.1.0
    - fiona==1.8.22
    - fonttools==4.38.0
    - gdal==3.5.3
    - geovoronoi==0.4.0
    - h3==3.7.4
    - hdbscan==0.8.29
    - igraph==0.10.2
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - numba==0.56.3
    - numpy==1.23.4
    - pandas==1.5.1
    - pillow==9.2.0
    - pyproj==3.4.0
    - pyrsistent==0.19.2
    - pysocks==1.7.1
    - pyyaml==6.0
    - rasterio==1.3.3
    - requests-toolbelt==0.10.1
    - rtree==1.0.1
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - semantic-version==2.10.0
    - sentry-sdk==1.12.1
    - shap==0.41.0
    - shapely==1.8.5.post1
    - simplejson==3.18.0
    - statsmodels==0.13.5
    - torch==1.12.1
    - unicodedata2==15.0.0
    - websocket-client==1.3.3
    - wrapt==1.14.1
    - wurlitzer==3.0.3
    - xgboost==1.7.1
